server:
  port: 8888
spring:
  application:
    name: sponsorship-config-server
  cloud:
   config:
    server:
      bootstrap: true
      git:
       uri: https://github.com/danielfeitosa/microservices-sponsorship
       default-label: main

