server:
  port: 0
spring:
  application:
    name: sponsor-service

  datasource:
   url: jdbc:h2:mem:sponsorshipdb
   driverClassName: org.h2.Driver
   username: sa
   password: password
  jpa:
   database-platform: org.hibernate.dialect.H2Dialect
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
