server:
  port: 8088
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: api-getway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true